"""
One-shot reproducer for HydraLM's five headline claims.

Usage
-----
    # CPU-cheap smoke run (~30s, matches the CI test-suite budget)
    python scripts/reproduce_claims.py --out RESULTS.md

    # Paper-budget run (2000 MQAR steps, 1M-token streaming probe)
    python scripts/reproduce_claims.py --budget paper --out RESULTS.md

    # JSON artifact for external dashboards / CI
    python scripts/reproduce_claims.py --json results.json

What it does
------------
Calls ``hydralm.eval.claims.run_all_claims`` to gate the five claims and
writes a Markdown results table (the same one referenced from the README)
plus an optional JSON blob. Exits non-zero if any claim fails, so CI can
use this as the single authoritative reproducer.

The actual numerical definitions of the gates live in
``hydralm/eval/claims.py``. This script is pure plumbing: budget selection,
rendering, and CLI.
"""
from __future__ import annotations

import argparse
import json
import platform
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import torch

from hydralm.eval.claims import ClaimReport, run_all_claims


# --------------------------------------------------------------------- budgets
# Each budget is a dict of ``{check_fn_name: overrides}`` that run_all_claims
# forwards into the individual claim checkers. "smoke" matches the CI test
# defaults; "paper" scales up the stress-tests that are worth more FLOPs.
BUDGETS: dict[str, dict[str, dict]] = {
    "smoke": {},
    "paper": {
        "check_claim_2_lossless_mqar": {
            "steps": 2000,
            "batch_size": 32,
            "lr": 3e-3,
        },
        "check_claim_3_constant_state": {
            "runtime_prefill": 4096,
            "runtime_stream": 512,
        },
        # For claim 6 the paper number is "1,000 new facts, 100% top-1
        # retrieval, ~16 MB state, no gradients" -- which requires
        # d >= n_facts for random keys to stay roughly orthogonal.
        "check_claim_6_online_learning": {
            "head_dim": 1024,
            "n_heads": 4,
            "n_facts": 1000,
            "argmax_threshold": 0.99,
        },
    },
}


# --------------------------------------------------------------------- render
def _check_mark(passed: bool) -> str:
    # Plain ASCII so the file renders identically everywhere.
    return "PASS" if passed else "FAIL"


def render_markdown(report: ClaimReport, budget: str, elapsed_s: float) -> str:
    """Render the report as a GitHub-flavoured Markdown page."""
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    torch_ver = torch.__version__
    py_ver = platform.python_version()
    device = "cuda" if torch.cuda.is_available() else "cpu"

    lines: list[str] = []
    lines.append("# HydraLM: Reproducible Results")
    lines.append("")
    lines.append(
        f"Generated by `scripts/reproduce_claims.py` "
        f"at `{now}`  "
        f"(budget: `{budget}`, runtime: `{elapsed_s:.1f}s`)."
    )
    lines.append("")
    lines.append(
        f"Environment: Python `{py_ver}`, PyTorch `{torch_ver}`, device `{device}`."
    )
    lines.append("")
    lines.append(f"**Overall status:** {'ALL PASS' if report.passed else 'FAILURE'}")
    lines.append("")

    # Summary table --------------------------------------------------------
    lines.append("## Claim summary")
    lines.append("")
    lines.append("| # | Claim | Status | Key measurement |")
    lines.append("|---|---|---|---|")
    for i, r in enumerate(report.results, start=1):
        key = _summary_key(r)
        lines.append(f"| {i} | {r.title} | {_check_mark(r.passed)} | {key} |")
    lines.append("")

    # Per-claim detail -----------------------------------------------------
    lines.append("## Per-claim detail")
    lines.append("")
    for i, r in enumerate(report.results, start=1):
        lines.append(f"### {i}. {r.title}  —  {_check_mark(r.passed)}")
        lines.append("")
        if r.notes:
            lines.append(f"_Notes:_ {r.notes}")
            lines.append("")
        lines.append("**Thresholds**")
        lines.append("")
        lines.append("```json")
        lines.append(json.dumps(r.thresholds, indent=2, default=str))
        lines.append("```")
        lines.append("")
        lines.append("**Measured**")
        lines.append("")
        lines.append("```json")
        lines.append(json.dumps(r.measured, indent=2, default=_json_default))
        lines.append("```")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "Reproducing this file: `python scripts/reproduce_claims.py "
        f"--budget {budget} --out RESULTS.md`"
    )
    lines.append("")
    return "\n".join(lines)


def _summary_key(r) -> str:
    """One-cell human-readable summary of the most interesting number."""
    m = r.measured
    if r.name == "claim_1_linear_complexity":
        return (
            f"HydraLM slope = **{m['hydra_slope']:.3f}**, "
            f"Transformer slope = {m['transformer_slope']:.3f}"
        )
    if r.name == "claim_2_lossless_mqar":
        return (
            f"HydraLM acc = **{m['hydra_accuracy']:.3f}**, "
            f"Transformer acc = {m['transformer_accuracy']:.3f} "
            f"(ratio = {m['ratio']:.2f})"
        )
    if r.name == "claim_3_constant_state":
        uniq = m["state_bytes_unique_values"]
        return f"state-bytes unique values across 1K..100M = **{uniq}** (want 1)"
    if r.name == "claim_4_cost_reduction":
        return (
            f"FLOP save = **{m['flop_save'] * 100:.1f}%**, "
            f"mem save = {m['mem_save'] * 100:.1f}%"
        )
    if r.name == "claim_5_drop_in":
        return (
            f"param ratio = **{m['param_ratio']:.3f}**, "
            f"HF generate ok = {m['hf_generate_ok']}"
        )
    if r.name == "claim_6_online_learning":
        mb = m["factbank_bytes"] / (1024 ** 2)
        ratio = m["kv_ratio"]
        return (
            f"argmax = **{m['argmax_accuracy'] * 100:.1f}%**, "
            f"overwrite margin = {m['overwrite_margin']:.2f}, "
            f"state = {mb:.2f} MB "
            f"({ratio:,.0f}x smaller than KV cache)"
        )
    return ""


def _json_default(obj):
    if isinstance(obj, (bool,)):
        return bool(obj)
    if hasattr(obj, "tolist"):
        return obj.tolist()
    return str(obj)


# --------------------------------------------------------------------- main
def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--budget", choices=tuple(BUDGETS), default="smoke",
        help="`smoke` = CI-speed defaults, `paper` = stronger numbers.",
    )
    p.add_argument("--out", type=Path, default=Path("RESULTS.md"),
                   help="Markdown report path.")
    p.add_argument("--json", type=Path, default=None,
                   help="Optional JSON artifact path.")
    p.add_argument("--quiet", action="store_true",
                   help="Suppress the per-claim progress line.")
    args = p.parse_args()

    overrides = BUDGETS[args.budget]
    if not args.quiet:
        print(f"[reproduce] running five-claim gate at budget={args.budget}")

    t0 = time.perf_counter()
    report = run_all_claims(overrides=overrides)
    elapsed = time.perf_counter() - t0

    if not args.quiet:
        for r in report.results:
            print(f"  [{_check_mark(r.passed)}] {r.name}: {_summary_key(r)}")
        print(f"[reproduce] done in {elapsed:.1f}s -> {args.out}")

    args.out.write_text(render_markdown(report, args.budget, elapsed))

    if args.json is not None:
        args.json.write_text(
            json.dumps(report.to_dict(), indent=2, default=_json_default)
        )
        if not args.quiet:
            print(f"[reproduce] wrote JSON -> {args.json}")

    return 0 if report.passed else 1


if __name__ == "__main__":
    sys.exit(main())
